### ISSUE TITLE
No create_dataset file inside data folder 

### ISSUE THREAD

**Issue by sumit1804** [SleepSupreme/GAN-for-Digital-Watermarks#2]
in `train.py` create_dataset function has been used which is imported from data/create_dataset.py  but in code there is not file named as create_dataset present.
![image](https://user-images.githubusercontent.com/111454227/232319357-e14572f0-ffdc-45b1-9560-06335bbaee5c.png)

No file named create_dataset in data folder.

![image](https://user-images.githubusercontent.com/111454227/232319412-aae5ccdc-0667-4976-9579-bfab3a8df900.png)

**Comment by sumit1804** [comment]
@chenguolin please help us on simulation. i would be very grateful to you.

**Comment by chenguolin** [comment]
Hi @sumit1804, the function `create_dataset()` is in the file `data/__init__.py` https://github.com/chenguolin/WatermarkFaker/blob/05647082947f5a2de9f9e0da96eb36a9e1462922/data/__init__.py#L47

**Comment by sumit1804** [comment]
@chenguolin  can you please help us to simulate this project by giving some points how can I simulate. As I am CSE undergrad and new to this field. I am facing very difficulty to simulate this project. Please help us on simulation. I would be very grateful to you.

**Comment by chenguolin** [comment]
To reproduce the method in the paper, you should first prepare a dataset of paired images `(original image, watermarked image)`. You can use the watermark functions in `watermarks/` to embed a watermark, which is an image of the same size as the cover image. Cover images can be from any dataset, such as CIFAR or ImageNet.

Our method is to train a neural network to learn the difference between the original images and the watermarked ones so that we can forgery the watermark embedding process by the trained neural network.
